### profile
spring.profiles.active=dev

### general
spring.application.name=database-backend
server.port=8881
server.servlet.context-path=/db
spring.devtools.livereload.enabled=true

# setting hibernate on WARN log level
#logging.level.org.hibernate.orm.core=warn

### defaults

## H2 DB

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

## Liquibase

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:h2:mem:testdb
spring.liquibase.user=sa
spring.liquibase.password=

## Logging

# Set the global logging level to INFO
#logging.level.root=info

# Set Spring to DEBUG so you can see why it routes or fails requests
logging.level.org.springframework.security=info
logging.level.org.springframework.web=INFO

# Set YOUR package to DEBUG to see your custom service/provider logs
# (Replace 'com.example' with your actual package name, like 'ro.cristiansterie.databasebackend....')
logging.level.com.example=debug

## JWT
jwt.secretKey=backend-super-secret-hex-string-that-is-long-enough-for-sha256
jwt.expiration=3600000

# health
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never