# dynamic port assgined by render.com
server.port=${PORT:8081}

## PostgreSQL DB - Supabase

# Supabase
#spring.datasource.url=jdbc:postgresql://db.umluxobmfsrfdbcxowze.supabase.co:5432/postgres?sslmode=require
#spring.datasource.username=postgres
#spring.datasource.password=P05TGR35Q11
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

## Liquibase

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.url=${DB_URL}
spring.liquibase.user=${DB_USER}
spring.liquibase.password=${DB_PASSWORD}

# Disable SQL init
#spring.sql.init.mode=never

##