## PostgreSQL DB - Supabase

# Supabase
spring.datasource.url=jdbc:postgresql://ep-proud-base-b2m1qmaw-pooler.c-6.eu-central-1.aws.neon.tech/database-dev?sslmode=require&channel_binding=require
spring.datasource.username=postgres
spring.datasource.password=npg_XPrJ9gnz6QkZ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

## Liquibase

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:postgresql://ep-proud-base-b2m1qmaw-pooler.c-6.eu-central-1.aws.neon.tech/database-dev?sslmode=require&channel_binding=require
spring.liquibase.user=postgres
spring.liquibase.password=npg_XPrJ9gnz6QkZ
spring.liquibase.drop-first=true

# Disable SQL init
#spring.sql.init.mode=never

##
