## PostgreSQL DB - Supabase

# Supabase
spring.datasource.url=jdbc:postgresql://db.ydlefioyjnzjdkjmmppf.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=P05TGR35Q11
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

## Liquibase

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:postgresql://db.ydlefioyjnzjdkjmmppf.supabase.co:5432/postgres?sslmode=require
spring.liquibase.user=postgres
spring.liquibase.password=P05TGR35Q11
spring.liquibase.drop-first=true

# Disable SQL init
#spring.sql.init.mode=never

##
